enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

npmAuthToken: "${PANDELL_NPM_TOKEN}"

npmPublishAccess: "public"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
